'use client';

import { Trash2, MessageSquare, Sparkles, Moon, Sun } from 'lucide-react';
import Image from 'next/image';

interface Chat {
  id: string;
    title: string;
      lastUpdated?: number;
      }

      interface ChatSidebarProps {
        chats: Chat[];
          activeChatId: string | null;
            onNewChat: () => void;
              onSelectChat: (id: string) => void;
                onDeleteChat: (id: string) => void;
                  onRenameChat: (id: string, title: string) => void;
                    darkMode: boolean;
                      onToggleDarkMode: () => void;
                      }

                      export default function ChatSidebar({
                        chats,
                          activeChatId,
                            onNewChat,
                              onSelectChat,
                                onDeleteChat,
                                  onRenameChat,
                                    darkMode,
                                      onToggleDarkMode,
                                      }: ChatSidebarProps) {
                                        const sortedChats = [...chats].sort(
                                            (a, b) => (b.lastUpdated || 0) - (a.lastUpdated || 0)
                                              );

                                                return (
                                                    <aside className="flex h-full w-[280px] flex-col border-r border-gray-200 bg-[#171717] dark:bg-[#171717] light:bg-[#f9f9f9]">
                                                          {/* Header */}
                                                                <div className="flex items-center justify-between p-4">
                                                                        <div className="flex items-center gap-2">
                                                                                  <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#10a37f]">
                                                                                              <Image
                                                                                                            src="/logo.svg"
                                                                                                                          alt="ShadMini AI"
                                                                                                                                        width={24}
                                                                                                                                                      height={24}
                                                                                                                                                                    className="rounded"
                                                                                                                                                                                />
                                                                                                                                                                                          </div>
                                                                                                                                                                                                    <span className="text-lg font-bold text-white">ShadMini AI</span>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                              onClick={onToggleDarkMode}
                                                                                                                                                                                                                                        className="flex h-8 w-8 items-center justify-center rounded-md border border-gray-600 text-gray-400 hover:bg-gray-800"
                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                          {darkMode ? <Sun size={16} /> : <Moon size={16} />}
                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                              {/* New Chat Button */}
                                                                                                                                                                                                                                                                                    <div className="px-4 pb-3">
                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                      onClick={onNewChat}
                                                                                                                                                                                                                                                                                                                className="flex w-full items-center justify-center gap-2 rounded-lg border border-gray-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-gray-800"
                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                  <Sparkles size={16} className="text-[#10a37f]" />
                                                                                                                                                                                                                                                                                                                                            <span>محادثة جديدة</span>
                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                {/* Info Box */}
                                                                                                                                                                                                                                                                                                                                                                      <div className="mx-4 mb-4 rounded-lg border border-[#10a37f]/30 bg-[#10a37f]/10 p-3 relative">
                                                                                                                                                                                                                                                                                                                                                                              <p className="text-xs text-gray-400 leading-relaxed pr-8">
                                                                                                                                                                                                                                                                                                                                                                                        مساعد ذكي متعدد النماذج للكتابة والترجمة والبرمجة
                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-gray-500 mt-1 pr-8">
                                                                                                                                                                                                                                                                                                                                                                                                                  التصميم بواسطة <strong className="text-[#10a37f]">ShadyRahimo</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <a
                                                                                                                                                                                                                                                                                                                                                                                                                                            href="https://t.me/AbuAlaX"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="absolute left-3 top-1/2 -translate-y-1/2 flex h-8 w-8 items-center justify-center rounded-full bg-[#2AABEE] text-white transition hover:bg-white hover:text-[#2AABEE] hover:border-2 hover:border-[#2AABEE]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm5.894 8.221l-1.97 9.28c-.145.658-.537.818-1.084.508l-3-2.21-1.446 1.394c-.14.18-.357.295-.6.295-.002 0-.003 0-.005 0l.213-3.054 5.56-5.022c.24-.213-.054-.334-.373-.121l-6.87 4.326-2.962-.924c-.635-.2-.647-.635.135-.957l11.566-4.458c.538-.196 1.006.128.832.943z"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Chat List */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex-1 overflow-y-auto px-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mb-2 px-1 text-xs font-semibold uppercase tracking-wider text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              المحادثات السابقة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {sortedChats.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="py-8 text-center text-xs text-gray-500">لا توجد محادثات</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="space-y-0.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {sortedChats.map((chat) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={chat.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`group flex cursor-pointer items-center gap-2 rounded-lg px-3 py-2.5 text-sm transition ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      chat.id === activeChatId
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? 'bg-[#343541] text-white'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : 'text-gray-400 hover:bg-gray-800 hover:text-white'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => onSelectChat(chat.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onDoubleClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const newTitle = prompt('اسم جديد:', chat.title);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (newTitle && newTitle.trim()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onRenameChat(chat.id, newTitle.trim());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <MessageSquare size={14} className="flex-shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="flex-1 truncate">{chat.title}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={(e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            e.stopPropagation();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (confirm('حذف المحادثة؟')) onDeleteChat(chat.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="opacity-0 group-hover:opacity-100 flex h-5 w-5 items-center justify-center rounded text-gray-500 hover:bg-red-500/20 hover:text-red-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Trash2 size={12} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }